### ISSUE TITLE
Blank view when referencing a Concourse 2.0 deployment

### ISSUE THREAD

**Issue by kdykeman** [dgodd/concourse-summary#8]
When I point to `https://concourse-summary-crystal.cfapps.io/host/<my_concourse_2_hostname>`, a page renders with the refresh countdown timer and GitHub link at the top.  The only other thing that is on the page is the "Show|Collapse Groups" link.

**Comment by kdykeman** [comment]
Digging into this a bit more, it looks like the v1 API was modified to include a `team/<teamname>` component.

i.e. This worked in 1.x - `https://<hostname>/api/v1/pipelines/<pipeline>/jobs/<job>`
but this works in 2.x - `https://<hostname>/api/v1/teams/<teamname>/pipelines/<pipeline>/jobs/<job>`

In addition, it looks like basic auth requires a team name as well.

**Comment by dgodd** [comment]
I'm sorry I took a while to answer this. I believe I fixed this a while back, see http://concourse-summary-crystal.cfapps.io/host/diego.ci.cf-app.com . Does it work for you now?

**Comment by kdykeman** [comment]
Sadly, it's still not working for me.  I'll have to dig a little more.

**Comment by dgodd** [comment]
@kdykeman, Is your pipeline public? If so can you give me its URL so I can attempt to debug?

**Comment by kdykeman** [comment]
Thanks @dgodd ... It is at a public URL.  I believe I've authorized your github account.
https://osl.ci.cf-app.com/

**Comment by dgodd** [comment]
At the moment it can't do github authorization, but can now do the 2x form of login if the `login_form` parameter is sent. Thus I believe that the below should work for you (but without a non github auth I can't test it)

```
http://concourse-summary-crystal.cfapps.io/host/osl.ci.cf-app.com?login_form
```

Does that work?

**Comment by kdykeman** [comment]
Worked like a charm!  Thanks for the help.
